services:
  - type: web
    name: morpheus-emr
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:PASSWORD@db.czifnstvmmstukcspoaq.supabase.co:5432/postgres
      - key: SESSION_SECRET
        generateValue: true
